/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ChatContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ChatMessage`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ChatView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useColorScheme.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useThemeColor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/chat/ChatContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/chat/ChatMessage`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/chat/ChatView`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../hooks/useColorScheme${`?${string}` | `#${string}` | ''}` | `/../hooks/useColorScheme.web${`?${string}` | `#${string}` | ''}` | `/../hooks/useThemeColor${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `/../constants/Colors${`?${string}` | `#${string}` | ''}` | `/../components/chat/ChatContext${`?${string}` | `#${string}` | ''}` | `/../components/chat/ChatMessage${`?${string}` | `#${string}` | ''}` | `/../components/chat/ChatView${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../hooks/useColorScheme`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useColorScheme.web`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useThemeColor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colors`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ChatContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ChatMessage`; params?: Router.UnknownInputParams; } | { pathname: `/../components/chat/ChatView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
